version: "3.8"
services:
  db:
    image: postgres:15.3-alpine
    container_name: pagamento-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data